# Generated by Django 4.1.1 on 2022-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingridient",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Название ингридиента"
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=20, verbose_name="Единицы измерения"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("is_favorited", models.BooleanField(default=False)),
                ("is_in_shopping_cart", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название рецепта"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="recipes/images/", verbose_name="Финальный результат"
                    ),
                ),
                ("text", models.TextField(verbose_name="Рецепт")),
                (
                    "cooking_time",
                    models.PositiveSmallIntegerField(
                        verbose_name="Время приготовления"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Название тега"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Цвет тега"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=70, unique=True, verbose_name="Slug"),
                ),
            ],
        ),
    ]
