# Generated by Django 4.1.1 on 2022-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(upload_to="recipes/images/", verbose_name="Фото"),
        ),
    ]
