# Generated by Django 4.1.1 on 2022-10-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_alter_recipeingredient_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="recipe_ingredient_exists",
        ),
    ]
