# Generated by Django 4.1.1 on 2022-10-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_remove_recipeingredient_recipe_ingredient_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                db_index=True, max_length=70, verbose_name="Название ингридиента"
            ),
        ),
    ]
